// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzsR-OQKnGBjOlK-yrCWtJPsO8_U8-mng',
    appId: '1:36004632059:android:3d4a6f3904ebecea59675e',
    messagingSenderId: '36004632059',
    projectId: 'anniba-gift',
    storageBucket: 'anniba-gift.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCorEtn_qjhujWQvo8YSrEgR5zPRRTzssA',
    appId: '1:36004632059:ios:574a0523fd32222e59675e',
    messagingSenderId: '36004632059',
    projectId: 'anniba-gift',
    storageBucket: 'anniba-gift.firebasestorage.app',
    iosBundleId: 'com.example.annibagift',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl_RVezREtscyTz-bWkbaMC94pknZmM5E',
    appId: '1:36004632059:web:9974417014fbe58659675e',
    messagingSenderId: '36004632059',
    projectId: 'anniba-gift',
    authDomain: 'anniba-gift.firebaseapp.com',
    storageBucket: 'anniba-gift.firebasestorage.app',
    measurementId: 'G-V2BL5E78V2',
  );

}